-- MySQL Script generated by MySQL Workbench
-- Wed Jan  6 13:47:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`author` ;

CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `uuidAuthor` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`uuidAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`book` (
  `uuidBook` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  `seriesname` VARCHAR(45) NULL,
  `uuidAuthor` VARCHAR(45) NULL,
  `isbn` VARCHAR(45) NULL,
  `price` DECIMAL NULL,
  PRIMARY KEY (`uuidBook`),
  INDEX `fk_book_author_idx` (`uuidAuthor` ASC) VISIBLE,
  CONSTRAINT `fk_book_author`
    FOREIGN KEY (`uuidAuthor`)
    REFERENCES `mydb`.`author` (`uuidAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `uuidUser` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `about` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`uuidUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `uuidReview` VARCHAR(45) NOT NULL,
  `uuidUser` VARCHAR(45) NULL,
  `uuidBook` VARCHAR(45) NULL,
  `value` INT NULL,
  `comment` VARCHAR(500) NULL,
  PRIMARY KEY (`uuidReview`),
  INDEX `fk_review_user_idx` (`uuidUser` ASC) VISIBLE,
  INDEX `fk_review_book_idx` (`uuidBook` ASC) VISIBLE,
  CONSTRAINT `fk_review_user`
    FOREIGN KEY (`uuidUser`)
    REFERENCES `mydb`.`user` (`uuidUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_book`
    FOREIGN KEY (`uuidBook`)
    REFERENCES `mydb`.`book` (`uuidBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
